accordproject/web-components

.github/workflows/pr.yml, .github/workflows/push.yml
=> chore(build) different GitHub CI workflow for push or PRs

packages/concerto-ui-react/src/lib/components/fields.js, packages/concerto-ui-react/src/lib/concertoForm.js, packages/concerto-ui-react/src/lib/reactformvisitor.js, packages/storybook/src/stories/1-MarkdownEditor.stories.js, packages/storybook/src/stories/3-ConcertoForm.stories.js
Fixes an issue flagged in https://github.com/accordproject/concerto-ui/pull/58 which was prematurely merged during the migration to web-components
=> fix(concertoForm): Properly update the cloned state on valueChange

package-lock.json, packages/cicero-ui/src/lib/ContractEditor/plugins/withClauses.js, packages/cicero-ui/src/lib/components/Clause/index.js, packages/cicero-ui/src/lib/components/styles.js
- Fixes a bug where clicking on the background of a clause would cause error from Slate in the console: `Connect resolve a Slate point from DOM point`.
=> fix(Clause): fix issue with background div causing slate error

packages/cicero-ui/src/environment/App/App.js, packages/cicero-ui/src/environment/App/App.spec.js, packages/cicero-ui/src/environment/App/index.js, packages/cicero-ui/src/lib/Counter/Counter.js, packages/cicero-ui/src/lib/Counter/Counter.spec.js, packages/cicero-ui/src/lib/Counter/index.js, packages/cicero-ui/src/lib/Counter/useLogic.js, packages/cicero-ui/src/lib/Counter/useLogic.spec.js, packages/cicero-ui/src/lib/Library/Buttons/index.js, packages/cicero-ui/src/lib/Library/Components/LibraryItemCard.js, packages/cicero-ui/src/lib/Library/index.js, packages/cicero-ui/src/lib/icons/remove.js
Fixes linter errors in cicero-ui package
=> style(cicero-ui): Fix linter errors

packages/concerto-ui/README.md
Create a `README` in sync with other packages
=> docs(conctero-ui): init readme

packages/ui-components/src/lib/Library/Components/CardActions.js
- Changes from Pull Request #128 to go into master
=> fix(Library): change onClick to onMouseDown to preserve Slate selection

packages/storybook/src/stories/3-ConcertoForm.stories.js, packages/ui-concerto/src/lib/components/concertoForm.js, packages/ui-concerto/src/lib/components/fields.js, packages/ui-concerto/src/lib/reactformvisitor.js
Same PR as #132 but pointing to master
=> fix(ConcertoForm): fix various bugs including DateTime error

package-lock.json, packages/ui-concerto/package.json, packages/ui-concerto/src/lib/components/fields.js
- Unfortunately, [Safari does not support](https://caniuse.com/#feat=input-datetime) the native `datetime-local` type for inputs. Therefore, I have introduced a library to use as the DateTime picker
- I'll make this same PR pointing to master after this one goes in
=> fix(ConcertoForm): fix DateTime picker for safari

package-lock.json, packages/ui-contract-editor/src/lib/ContractEditor/plugins/withVariables.js
Prevent <kbd>SHIFT</kbd> + <kbd>ENTER</kbd> inside variable
=> fix(ui-contract-editor): prevent variable splice - I74

package-lock.json, packages/storybook/package.json, packages/ui-contract-editor/package.json, packages/ui-markdown-editor/package.json
=> chore(dep) Upgrade to Markdown Transform 0.12.3 & Cicero 0.21.2

package-lock.json, packages/storybook/package.json, packages/ui-concerto/package.json, packages/ui-contract-editor/package.json, packages/ui-markdown-editor/package.json
- Upgrades to latest Markdown Transform `0.12.4` and Cicero `0.21.3`
=> chore(release) Upgrade for Cicero 0.21.3

packages/storybook/src/stories/4-ContractEditor.stories.js, packages/storybook/src/stories/__snapshots__/1-MarkdownEditor.test.js.snap, packages/storybook/src/stories/__snapshots__/4-ContractEditor.test.js.snap, packages/storybook/src/stories/__snapshots__/7-Library.test.js.snap, packages/ui-contract-editor/src/lib/ContractEditor/index.js, packages/ui-contract-editor/src/lib/ContractEditor/plugins/withClauses.js, packages/ui-contract-editor/src/lib/components/Clause/index.js, packages/ui-contract-editor/src/lib/components/styles.js
- feat(Clause): show red border on parse error
- unrelated change - updates snapshot tests from previous changes
- updates story to print out parse result or error in storybook actions tab
=> feat(Clause): show red border on parse error

package-lock.json, packages/storybook/src/stories/4-ContractEditor.stories.js, packages/ui-contract-editor/src/lib/ContractEditor/plugins/withClauses.js, packages/ui-contract-editor/src/lib/index.js, packages/ui-contract-editor/src/lib/utilities/getChildren.js
Signed-off-by: Dan Selman <danscode@selman.org>
Update formulas when dependent variables are modified.
- detect when a Clause node contains formulas, redraft and update the values of the formulas in the editor
- efficiency could be improved by tagging templates as containing formulas, or by using caching. As implemented the check for formulas in the Slate DOM happens on every change
https://www.loom.com/share/acf83a0c298e4f99b909cfbfb0311ec7
=> feat(ui-contract-editor): update formulas when dependent variables change

packages/ui-contract-editor/src/lib/components/Formula/index.js, packages/ui-contract-editor/src/lib/styles.css
- fix(formula): fix tooltip flickering and crash when clicking formula
=> fix(formula): fix tooltip flickering and crash when clicking formula

package-lock.json, packages/storybook/package.json, packages/ui-contract-editor/package.json, packages/ui-markdown-editor/package.json
- chore(deps): update transforms to 0.12.5
=> chore(deps): update transforms to 0.12.5

package-lock.json, packages/storybook/package.json, packages/ui-contract-editor/package.json, packages/ui-markdown-editor/package.json
- Upgrades to markdown transform `0.12.6` fixing issues with conditionals and optionals
- Upgrades to Cicero `0.21.4` fixing issues with quoting in formulas
=> chore(deps): update transforms to 0.12.6 ; cicero to 0.21.4

packages/ui-contract-editor/src/lib/ContractEditor/index.js, packages/ui-contract-editor/src/lib/components/Formula/index.js, packages/ui-contract-editor/src/lib/styles.css
- refactor(Formula): refactor code and fix so that dependencies are not hardcoded
- fix(formula): fix hovering style so it does not overlap actual formula and shows pointer triangle
- fix(formula): fixes issue where clicking formula multiple times in safari causes crash
- feat(formula): change style to have different font color with no border
=> feat(formula): updates and fixes

package-lock.json, packages/storybook/package.json, packages/ui-concerto/package.json, packages/ui-contract-editor/package.json, packages/ui-markdown-editor/package.json
- Upgrade markdown transform to `0.12.9` with some bug fixes & model decorators in Slate
- Upgrade to Cicero `0.21.7`
=> chore(dep) Upgrade to latest markdown transform and Cicero

packages/ui-markdown-editor/src/lib/FormattingToolbar/ToolbarMenu.js, packages/ui-markdown-editor/src/lib/index.js
Re-align UI to Accord Project spec
- adjust box shadow to spec (5px bottom)
- add border to Editable component (1px gray, 4px radius)
=> style(src): add border to Editable component - I51

packages/ui-concerto/src/lib/components/concertoForm.js
- feat(concertoForm): allow updating form via json prop
- <TWO>
- <ONE>
- <TWO>
- Issue #<NUMBER>
=> feat(concertoForm): allow updating form via json prop

packages/ui-markdown-editor/package.json, packages/ui-markdown-editor/src/lib/components/Leaf.test.js
Signed-off-by: YYee <ongyernyee@gmail.com>
- updated npm script test with SKIP_PREFLIGHT_CHECK mode
- created sample test
=> test(ui-markdown-editor): add rtl with sample test - 192

packages/ui-markdown-editor/src/lib/FormattingToolbar/HyperlinkModal.js, packages/ui-markdown-editor/src/lib/index.js
Signed-off-by: Sahal Saad <caalshift@gmail.com>
- Change way to fix the previous bug.
- N/A
- Issue #47 
- Pull Request #207
=> fix(ui-markdown-editor): Fix broken hyperlink shortcut - 211

packages/ui-markdown-editor/src/lib/plugins/withLinks.js
Signed-off-by: Sahal Saad <caalshift@gmail.com>
- Add isCollapsed condition when link click/select.
- <ONE>
- <TWO>
- Issue #<NUMBER>
=> fix(ui-markdown-editor): Fix cannot select link - 114

packages/ui-markdown-editor/src/FormattingToolbar/HyperlinkModal.js, packages/ui-markdown-editor/src/FormattingToolbar/index.js
- <ONE> Changed the index.js and HyperlinkModal.js in ui-markdown-editor
- <TWO> Styling changes done in above files
- <ONE> Had to style the components according to the screen size by hit and trial and observing different breakpoints.(brute force method)
- <TWO> Had to reduce modal width to ensure it fits (screens less than 335px have not been adjusted)
- Issue #219 <NUMBER>
=> fix(ui-markdown-editor): resolve hyperlink overflow - I219

packages/ui-components/src/Library/Components/LibraryItemCard.js
Signed-off-by: Dan Selman <danscode@selman.org>
Merging: https://github.com/accordproject/web-components/pull/234 from @naveen8801
=> fix (library) : Long template name intersects with Logo (#184)

packages/ui-contract-editor/src/ContractEditor/plugins/withVariables.js
…#212)
- Check whether the variable is editable or not.
- A condition is added which checks it and prevents editing of the variable if it is read-only.
- Issue #212
=> fix(ui-contract-editor) prevent sig variable edits on readOnly - I212

package.json
Signed-off-by: Aniruddha Shriwant <aniruddhashriwant@gmail.com>
<OVERALL SUMMARY OF PULL REQUEST>
- Added Package Repository Information<INSERT DESCRIPTION OF CHANGES>
=> feat(package): add repository information to package.json

README.md
- Script for user interaction testing needed to be corrected in the readme file.
- Issue #14
=> docs(readme): interaction test script corrected

README.md
- From Google, I found that React is a JavaScript Library, not a framework. Hence I updated it in the doc.
- Reference Image
- Modification Image
=> docs(README): update correct info about React
