accordproject/web-components

packages/markdown-editor/src/lib/FormattingToolbar/HyperlinkButton.js
The `ref` was removed [here](https://github.com/accordproject/markdown-editor/commit/2e5de62b7b817620fdf51983355e1470d43c2340) but reappeared during the code transfer.
My editor also auto-fixed some linting when I saved.
=> fix(HyperlinkButton): remove unused ref

DEVELOPERS.md, packages/cicero-ui/src/lib/ContractEditor/plugins/withVariables.js
Prevents deleting backwards at the beginning of a variable
- Provide more documentation for reloading in local development
- Check for backward delete event if at the beginning of a variable
- N/A
=> fix(cicero-ui): prevent backspace at variable start - I78

packages/cicero-ui/src/lib/index.js
This fixes an issue where semantic-ui styles were interfering with other styles when using this app in a third party. For reference, the third party also uses semantic-ui and includes semantic-ui's css stylesheet in the head of its html page.
Removing this import does not seem to have any negative impact. Both markdown-editor and concerto-ui-react also use semantic-ui and did not have this import in the library itself (I do see it in the story for Contract Editor and Markdown Editor).
=> fix(cicero-ui): remove semantic-ui stylesheet

package-lock.json, packages/cicero-ui/src/lib/ContractEditor/index.js, packages/cicero-ui/src/lib/components/Clause/index.js
fix(Clause): pass readOnly props to clause to not render icons
=> fix(Clause): pass readOnly props to clause to not render icons

packages/cicero-ui/src/lib/ContractEditor/plugins/withClauses.js
feat(withClauses): adds canAddClause query to editor to call when adding a clause to prevent adding clauses in nested elements such as lists or other clauses
=> feat(withClauses): adds canAddClause query to editor

packages/cicero-ui/src/lib/Library/README.md, packages/cicero-ui/src/lib/Library/index.js
Adds `cicero-ui__library-cards-wrapper` CSS class to library cards wrapper element. Helps in setting the desired height. It is useful when the collection is large.
=> style(Library): Add utility class to library cards wrapper

packages/cicero-ui/src/lib/components/styles.js
feat(Clause): update styling so less space at top of clause
Shown below with not hovering and hovering for different clauses.
=> feat(Clause): update styling so less space at top of clause

packages/markdown-editor/src/lib/utilities/generateId.js
Improve `id` generation for headings
- Reduce all children of a header to include formatted text
- https://github.com/accordproject/markdown-editor/pull/377
=> feat(markdown-editor): generate id on whole header

packages/cicero-ui/src/lib/ContractEditor/README.md, packages/cicero-ui/src/lib/ContractEditor/plugins/withClauses.js
`onClauseUpdated` was being passed a clause node in all cases except this one, which passed the editor instead
- Update documentation on optional functionality
- Pass the clause node and a boolean instead of the editor `onClauseUpdated`
- Unsure how this was introduced from the [original code](https://github.com/accordproject/cicero-ui/blob/master/src/ContractEditor/plugins/withClauses.js#L119)
- PR https://github.com/accordproject/web-components/pull/4
=> fix(ContractEditor): correct onClauseUpdated call

packages/storybook/src/stories/4-ContractEditor.stories.js
- feat(ContractEditorStory): update story to insert clause at end of document on clause change
- This fixes the bug we saw earlier today when using the dropdown to select a new clause and also allows us to test multiples clauses in the storybook by adding the clause to the document instead of re-rendering it with the chosen clause
- Also removes an unused `ref` from the storybook component
=> feat(ContractEditorStory): update story to insert clause at end of document on clause change

packages/ui-contract-editor/src/lib/components/Clause/index.js
- Adds a workaround for children of draggable elements not being editable in Safari by removing draggable attribute when user is inside the text of a clause
=> fix(Clause): fixes clauses being uneditable in safari when draggable - #115 

packages/ui-contract-editor/src/lib/ContractEditor/index.js, packages/ui-markdown-editor/src/lib/index.js, packages/ui-markdown-editor/src/lib/plugins/withImages.js
- feat(*): add drag and drop for images
- Images are inlines and should be displayed as such (previously, we were displaying them as "block" elements
- Therefore, I am now displaying them as inline and allowing them to be dropped inline (unlike clauses which we force to be dropped at the top level)
- Issue #61
=> feat(*): add drag and drop for images

packages/ui-contract-editor/src/lib/ContractEditor/index.js
Enhance backspace checking to handle backspacing immediately after a clause template
- Check used to be if the cursor was at the end of the document, without a selection, and after a clause template
- Check is now if the cursor is beginning at the start of a node and the previous node is a clause template
- Publishing this will include the parser changes upstream
- Pull Request https://github.com/accordproject/cicero-ui/pull/412
=> fix(contract-editor): protect clause from backspace - I122

package-lock.json, packages/storybook/package.json, packages/storybook/src/stories/4-ContractEditor.stories.js, packages/ui-contract-editor/package.json, packages/ui-markdown-editor/package.json
Support the new parser from `cicero`
- Upgrade `markdown-transform` and `cicero`
- My branch should be up to date, not sure what's happening in `package.json`
- Issue https://github.com/accordproject/cicero/issues/547
=> refactor(*): upgrade to new parser

packages/ui-components/src/lib/Library/Components/CardActions.js
- fix(Library): change `onClick` to `onMouseDown` to preserve Slate selection when adding a clause from the Library component (see https://slate-js.slack.com/archives/C1RH7AXSS/p1587510249444700)
- Requesting to merge into the v0.93 branch so we can get this bug fix out before finishing the work on the new parser. This fix will also need to be merged into master as well at some point.
=> fix(Library): change onClick to onMouseDown to preserve selection

packages/storybook/src/stories/3-ConcertoForm.stories.js, packages/ui-concerto/src/lib/components/concertoForm.js, packages/ui-concerto/src/lib/components/fields.js, packages/ui-concerto/src/lib/reactformvisitor.js
- Fixes DateTime error that caused crash. The value supplied by the form on change is already an ISO string, so we shouldn't use `toISOString` on it, unless there is no value (ie. we just changed the model to be DateTime), then use `new Date().toISOString()` to get the current date/time. Slice on the string was changed from `(0,19)` to `(0,16)` to exclude seconds.
- Fixes issue where empty strings were not allowed as values because `e.value` on an empty string is falsey and `e.target.value` would throw an error in the console.
- Adds keys to iterable React components where necessary
- Removed `types` from onModelChange storybook action because it throws an error in the console and does not log as a storybook action.
- I'll make this same …
=> fix(ConcertoForm): fix various bugs including DateTime error

package-lock.json, packages/storybook/src/stories/1-MarkdownEditor.stories.js, packages/storybook/src/stories/__snapshots__/1-MarkdownEditor.test.js.snap, packages/storybook/src/stories/__snapshots__/4-ContractEditor.test.js.snap, packages/ui-markdown-editor/src/lib/components/Node/Heading.js, packages/ui-markdown-editor/src/lib/components/index.js, packages/ui-markdown-editor/src/lib/utilities/constants.js
- Match the style of headings in the contents to that of the preview headings in the dropdown toolbar
- (Markdown Editor Heading.js) Removed 'serif' as default font-family for headings in dropdown toolbar for in favour of inheriting common base style
- New dropdown style constants added for H4 to H6
- BaseElementRenderer to use dropdown style constants 
- Fixed Markdown Editor storybook demo to use correct tags from h1 to h6
- Update snapshots to reflect new styles from markdown editor
- Updated Contract Editor snapshot (style attribute of id="Heading-One")
- Updated Markdown Editor snapshot (headings styles)
- This change contains new base snapshots for tests
#103
=> feat(ui-markdown-editor): match style of dropdown headings - i103

package-lock.json, packages/storybook/package.json, packages/storybook/src/stories/4-ContractEditor.stories.js, packages/ui-contract-editor/package.json, packages/ui-contract-editor/src/lib/ContractEditor/index.js, packages/ui-contract-editor/src/lib/ContractEditor/plugins/withClauseSchema.js, packages/ui-contract-editor/src/lib/components/Optional/OptionalBoolean.js, packages/ui-contract-editor/src/lib/components/Optional/OptionalSwitch.js, packages/ui-contract-editor/src/lib/components/Optional/index.js, packages/ui-contract-editor/src/lib/components/styles.js, packages/ui-contract-editor/src/lib/styles.css, packages/ui-markdown-editor/package.json
Support `optional` variable types - conditionals with variables in them
- Used very similar code to `conditional` variable support
- Did need to repeat code from `Conditional`, DRY'd it as much as I could
- `Node.string(node)` can replace [`childReducer`](https://github.com/accordproject/web-components/blob/master/packages/ui-contract-editor/src/lib/components/actions.js#L21) from https://github.com/accordproject/web-components/pull/117
- Spacing (margin/padding) for variable inside optional could use work
- https://github.com/accordproject/cicero/issues/549
=> feat(*): init optional variable support - I145

packages/ui-markdown-editor/src/lib/utilities/toolbarHelpers.js
- fix(toggle block of toolbar helpers getting node and path from node descendants ):add 0 to the element before last in anchor and focus-#134
- https://github.com/accordproject/web-components/issues/134
=> fix(ui-markdown-editor): add 0 to element before last in anchor and focus - i134

packages/ui-components/src/lib/Library/Buttons/index.js
Signed-off-by: Aman Sharma <mannu.poski10@gmail.com>
Add a prop to provide functionality for the user to upload their own template
=> feat(ui-components): add prop to upload template in the library component

package-lock.json, packages/storybook/src/stories/4-ContractEditor.stories.js, packages/ui-contract-editor/src/lib/ContractEditor/index.js, packages/ui-contract-editor/src/lib/ContractEditor/plugins/withClauses.js
- Allows editing of the clause text if that clause has a `parseable` property set to `false` on its data object
- Updates the `onClauseUpdated` function to replace the clause node if it receives a new clause node after parsing
- Adds new helper function `getClauseWithPath` and refactors previous code to use it where applicable
~~- If an `onClauseUpdated` method is passed to the ContractEditor component, the Contract Editor now expects it to return an array where the first element is whether or not the clause successfully parsed as a boolean and the second is an optional new node to replace the previous clause node.~~
- If an `onClauseUpdated` method is passed to the ContractEditor component, the Contract Editor now expects it to return an …
=> feat(ui-contract-editor): updates to parsing and refactors code

packages/ui-concerto/src/lib/components/fields.js
- fix(ui-concerto): fallback to regular input field if cannot parse relationship
- Parsing a relationship with `Relationship.fromURI` will fail for older templates that do not use `resource:Type#Identifier`. In this case, fall back to the regular input field.
=> fix(ui-concerto): fallback to regular input field if cannot parse relationship

packages/ui-contract-editor/src/lib/components/Formula/index.js
Noticed two edge cases for the tooltip that this fixes:
- Makes sure it is positioned right above formula element no matter the size of the tooltip
- Adds z-index 2 to make sure it floats over clause icons if it is high up in the clause
=> fix(formula): fixes edge cases for positioning tooltip

package-lock.json, packages/storybook/package.json, packages/ui-contract-editor/package.json, packages/ui-markdown-editor/package.json
- Upgrades to cicero `0.21.5` and markdown transform `0.12.7`, fixing issues with nested blocks
=> chore(dep) Upgrade to Cicero 0.21.5 and markdown transform 0.12.7

package-lock.json, packages/storybook/src/stories/1-MarkdownEditor.stories.js, packages/ui-contract-editor/src/lib/ContractEditor/index.js, packages/ui-markdown-editor/src/lib/components/index.js, packages/ui-markdown-editor/src/lib/index.js, packages/ui-markdown-editor/src/lib/plugins/withLists.js, packages/ui-markdown-editor/src/lib/utilities/hotkeys.js, packages/ui-markdown-editor/src/lib/utilities/toolbarHelpers.js
Signed-off-by: Dan Selman <danscode@selman.org>
Also: https://github.com/accordproject/web-components/issues/182
Also: https://github.com/accordproject/web-components/issues/49
Also: https://github.com/accordproject/web-components/issues/41
- Adds a keyboard handler for SHIFT+ENTER which inserts a LINEBREAK into the Slate DOM
- HTML copy/paste requires a fix in markdown-html
https://www.loom.com/share/a1458a6fece0468088e2fef776e99d8f
=> feat(markdown-editor) : SHIFT+ENTER inserts a linebreak

packages/ui-markdown-editor/src/lib/index.js
Signed-off-by: Yang Wei Hao <whyang0808@gmail.com>
- fix(ui-markdown-editor): close hyperlink modal when user is not interacting with it
=> fix(ui-markdown-editor): close hyperlink modal when not interacting i47

packages/ui-markdown-editor/src/lib/FormattingToolbar/HyperlinkModal.js
- <ONE>Implement link copied message in HyperlinkModal
- <TWO>
- <ONE>
- <TWO>
- Issue #50 
- [/ ] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
=> feat(ui-markdown-editor): Implement link copied message - 50

packages/ui-markdown-editor/src/lib/FormattingToolbar/StyleFormat/index.js
Signed-off-by: Sahal Saad <caalshift@gmail.com>
- Fix flashing at style format
- I am not sure why previously use `useSlate`. Cannot trace from git history.
- Issue #<NUMBER>
=> fix(ui-markdown-editor): Fix flashing at style format - 97

packages/ui-markdown-editor/src/FormattingToolbar/HyperlinkModal.js
- <ONE>Removed the transition property in hyperlink modal styles
- <ONE> The Modal will now no longer appear via transition and will appear instantly
=> style(ui-markdown-editor): remove link modal fade-in effect - I218

package-lock.json, packages/storybook/src/stories/4-ContractEditor.stories.js, packages/ui-contract-editor/package-lock.json, packages/ui-contract-editor/package.json, packages/ui-contract-editor/rollup.config.js, packages/ui-contract-editor/src/ContractEditor/plugins/withClauses.js
Signed-off-by: K-Kumar01 <kushalkumargupta4@gmail.com>
Fixed the deprecated uuid import. 
- <ONE> Deprecated uuid import resolved.
- <TWO> No warning logged in the console.
- <ONE> uuid deprecated import issue resolved
=> fix(main): deprecated uuid import fix - I224

packages/ui-contract-editor/src/styles.css
Z-index of tooltip changed to prevent the overlapping by template
- Changed z-index of tooltip
=> fix(ui-contract-editor): adjust tooltip z-index - I185

packages/ui-markdown-editor/src/utilities/constants.js
Signed-off-by: Udbhavbisarya23 <udbhavbisarya46.ub@gmail.com>
Changed Heading and Made changes to font sizes of ui-markdown-editor
- Center Aligned the H1 tags
- Changed font size and line height of h4,h5 and h6tags to 15,14 and 13 px respectively (As it is in PDF)
=> feat(ui-markdown-editor): center align h1 tags - I146

packages/ui-contract-editor/src/ContractEditor/index.js
…list - #157
- Drag and Drop possible for both:
- Inside The List: 'edge' = focus, Transform.select(editor, targetRange)
- Oustside The List: Only able to place above the list, selects the previous child component using Transform.select, 'edge'=end
- When dropping outside the list the drag and drop icon/cursor of the clause should be placed after the list-item text.
- When dropping inside the list the drag and drop icon/cursor of the clause should be placed at the start of the list-item text.
-Demo Outside the list: https://www.loom.com/share/954e26d39c114443a2057c6a082e9088
-Demo Inside the list: https://www.loom.com/share/0b52426ebd154db8958adf5c7a0822ad
- Issue #157
=> fix(ui-contract-editor): prevent clause drag and drop in list - I157

packages/ui-contract-editor/src/ContractEditor/plugins/withVariables.js
- Code commented in isEditableVariable in withVariables.js
[https://www.loom.com/share/91e95c6d657e40d48d41cf41e2da0812](url)
- Issue #150
=> feat(ui-contract-editor):string variable can be made empty(#150)

packages/ui-markdown-editor/src/utilities/toolbarHelpers.js
Signed-off-by: Gatij Taranekar <gatij.taranekar@gmail.com>
- <ONE> Added another condition for checking node type as headings in the if block.
https://www.loom.com/share/a417c8136e954883b281c8b1e74fe254
- Issue #158 
- Pull Request #252
=> fix(ui-markdown-editor): list formatting is preserved in headings

packages/ui-markdown-editor/src/utilities/toolbarHelpers.js
Choosing multiple paragraphs and then converting them to list will now show points-bullet or numbers along with the indentation
- Need to change the anchor and focus when selecting from bottom
Selecting from bottom
Result
=> fix(ui-markdown-editor):multi-para to list proper indent - I158

packages/ui-contract-editor/src/components/Clause/index.js
- String match with clause header, if header length is 0 then disable the clause ui-icons.
- padding added to clause wrapper
- Issue #178
=> feat(ui-contract-editor):drag&drop disabled for embeded clauses

packages/ui-markdown-editor/src/FormattingToolbar/ToolbarMenu.js
Signed-off-by: Udbhavbisarya23 <udbhavbisarya46.ub@gmail.com>
- <ONE> The z-index of the formatting toolbar is changed from 10. No z-index assigned
- Issue #87
=> bug(ui-contract-editor): remove z-index of toolbar - I87

package-lock.json, packages/storybook/src/stories/3-ConcertoForm.stories.js, packages/ui-concerto/package.json, packages/ui-concerto/src/__snapshots__/formgenerator.test.js.snap, packages/ui-concerto/src/components/__snapshots__/concertoFormWrapper.test.js.snap, packages/ui-concerto/src/components/concertoForm.js, packages/ui-concerto/src/components/concertoFormWrapper.test.js, packages/ui-concerto/src/components/fields.js, packages/ui-concerto/src/formgenerator.js, packages/ui-concerto/src/formgenerator.test.js, packages/ui-concerto/src/reactformvisitor.js, packages/ui-concerto/src/utilities.js, packages/ui-concerto/test/data/relationship.cto, packages/ui-concerto/test/data/specialTypes.cto, packages/ui-concerto/test/data/specialTypes.json
Upgrades `ui-concerto` to use `@accordproject/concerto-core@1.0.0-alpha.2`, and improves testing coverage.
- Follows the changes in the Concerto migration guide, https://docs.accordproject.org/docs/next/ref-migrate-concerto-0.82-1.0.html
- Adds unit tests for `identified` keyword
- Adds unit test for array buttons (add / remove element). And fixed a related bug in the value provided to `onValueChange`.
- Adds unit tests for the built-in "special types" such as `MonetaryAmount` which has a special rendering path 
- Storybook now uses the built-in HTML entity escaping rather than our custom escaping
- Improves A11Y by adding `htmlFor` labels to input fields. This also makes testing easier.
File                  |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s | …
=> feat(ui-concerto): Upgrade to Concerto v1.0

README.md
This typo was causing the ``404`` error as it was not linking to the contract editor repository. It works now.
```diff
- [Contract Editor](packages/ui-contract-edtior): An editor based on our [Markdown Editor](packages/ui-markdown-editor) for handling smart legal contracts.
+ [Contract Editor](packages/ui-contract-editor): An editor based on our [Markdown Editor](packages/ui-markdown-editor) for handling smart legal contracts.
```
- Issue #274
=> fix(ui-markdown-editor): typo in readme - #274

packages/ui-contract-editor/src/components/Clause/index.js, packages/ui-contract-editor/src/components/styles.js, packages/ui-contract-editor/src/icons/drag.js
Styling changes applied to the drag & drop handle so that short clauses don't have large space.
- <ONE> Changes in margin
- <TWO> Some changes in svg and height
=> style(ui-contract-editor): Drag-Drop Handle Resize - I137

packages/ui-markdown-editor/src/FormattingToolbar/StyleFormat/index.js, packages/ui-markdown-editor/src/FormattingToolbar/index.js, packages/ui-markdown-editor/src/index.js
Before this, the styles block would not refresh when we changed the cursor position. It would only refresh when we started writing. Now the styles block gets updated when the cursor position changes.
- <ONE> New ``currentStyle`` value gets initiated in ``useState`` hook. That ``currentStyle`` now gets updated inside the ``onChange`` function which makes this work.
- <TWO> Then ``currentStyle`` value gets passed down to the ``StyleDropdown`` menu through props.
- This still does not work for ``Heading 4``, ``Heading 5``, and ``Heading 6`` as they are not yet decided upon but would work normally if they are included later in the future. But the empty bar would be replaced with ``"Style"`` for now.
- See #280 for updates. …
=> fix(ui-markdown-editor): styleblock refresh - #276

packages/ui-markdown-editor/src/FormattingToolbar/StyleFormat/index.js
Beforehand, selecting any kind of text and then clicking on the dropdown menu used to dismiss the selection. Now clicking on the drop-down menu does not affect the selected text.
- A new function was added called `onMouseDownHandler` which was routed to the `onMouseDown` prop for the dropdown menu.
- This function includes `event.preventDefault()` which fixes the issue.
=> fix(ui-markdown-editor): text deselection - #291

packages/ui-markdown-editor/src/index.js
The Cut operation that can't be performed upon the images is regulated.
- Click an image
- Press Ctrl+X
- Image disapperas 
- Normal cut functionality
- Issue #294 
=> fix(ui-markdown-editor): handle cut image operation - #294

packages/ui-markdown-editor/src/FormattingToolbar/ToolbarMenu.js
The styling dropdown was being obscured by the clause template. This fixes the issue by pulling up the z-index of the toolbar so that it appears above the template.
- Added a `z-index` to the toolbar
- Removed a dead closing curly brace that was probably left there mistakenly as there was no opening bracket and it was giving out a red line.
- We probably need to organize the `z-index` of all the elements in order to avoid confusion in the future. This is how it looks like.
The issue is resolved.
=> fix(ui-contract-editor): styling dropdown - #278

packages/ui-markdown-editor/src/plugins/withLinks.js
Creating a hyperlink by selecting the text now changes the text in the markdown.
- <ONE> Delete the current selection
- <TWO> Insert the node with updated parameters.
https://www.loom.com/share/6eb14ef12e6243c2bf7ad810f1795240
https://www.loom.com/share/8c31c14ea6e8468b852b272a1f3aed49
=> fix(ui-markdown-editor): hyperlink markdown text conversion - #301

packages/ui-markdown-editor/src/FormattingToolbar/StyleFormat/index.js, packages/ui-markdown-editor/src/utilities/constants.js, packages/ui-markdown-editor/src/utilities/toolbarHelpers.js
- Added Heading 4, Heading 5, and Heading 6 and change font sizes of existing heading in the following manner:
- `Heading 1` = 25px => Stays the same
- `Heading 2` = 25px => Left-aligned to differentiate from H1
- `Heading 3` = 20px
- `Heading 4` = 18px
- `Heading 5` = 16px
- `Heading 6` = 14px => Same size as a normal paragraph, All capital letters, The same text formatting as the text used in Page Break
- Added new headings in the `isBlockHeading` function that tells if a block is heading or not.
- There are few problems existing in the headings especially `Heading 6`. This is basically occurring because a few of the CSS properties are not defined so to make things look better, web browsers add them by default under …
=> feat(ui-markdown-editor): heading refactor - #293

packages/ui-markdown-editor/src/components/icons/image.js, packages/ui-markdown-editor/src/components/icons/tbreak.js
Clickable area increased of page break and image icons.
- <ONE> Updated the width and padding of the icons
**The height of different icons**
**Hovering over the icon**
=> fix(ui-markdown-editor): Resize clickable area - #318

packages/ui-markdown-editor/src/index.js, packages/ui-markdown-editor/src/plugins/withText.js
Beforehand, doing `---` did not do anything and kept the text as it is but doing that now inserts a page break.
This will only insert a page break on a new line.
- Added a new file `withText` that will handle all the new shortcuts that will be created from now based on just entering text.
- <ONE> Page Break keyboard shortcut does not work yet but the solution is in progress at #270
- Issue #259, #263 
- Pull Request #270
=> feat(ui-markdown-editor): direct page break - #276

packages/ui-markdown-editor/src/index.js
Signed-off-by: Dan Selman <danscode@selman.org>
Catches exceptions raised by the `onChange` handler registered with the markdown-editor, preventing them from crashing the editor.
- Wrap `onChange` in try/catch and log to the console
=> Catch onChange exceptions for issue #335

packages/ui-markdown-editor/src/index.js
Image can be deleted now by pressing either the backspace key or the delete key.
- <ONE> Check if the key is backspace and node selected is image. If `true` delete the use `Editor.deleteBackward(editor)`
- <TWO> Check if the key is delete and node selected is image. If `true` delete the use `Editor.deleteFordward(editor)`
=> fix(ui-markdown-editor): allow image deletion - #320

packages/ui-markdown-editor/src/components/Leaf.js
Signed-off-by: Devesh <deves125@gmail.com>
This pull request adds a light grey background color to the inline code area.
- Added a light grey background to the inline code.
- Added a very thin `1px` border to that `inline_code` area and `2.5px` border-radius.
=> feat(ui-markdown-editor): inline-code BG - #341

packages/ui-markdown-editor/src/plugins/withText.js, packages/ui-markdown-editor/src/utilities/matchCases.js
Signed-off-by: Devesh <deves125@gmail.com>
This pull request adds the feature of markdown shortcuts for headings. Now we can insert headings in the document with the help of just the `#`.
- \# => H1
- \## => H2
- \### => H3
- \#### => H4
- \##### => H5
- \######=> H6
- ---,  - - -, ***, * * * => PageBreak
- This is a refactor to the #347 which was suggested by @dselman [here](https://github.com/accordproject/web-components/pull/347#discussion_r634371097).
- I could be wrong in understanding what Dan was saying. I want to get the opinions of Dan and other mentors on how to implement the structure for the `matchCases` so it becomes very easy to implement more matching functions later in the future.
- <ONE> A file called `matchCases` is added inside the `utilities` folder. This file is …
=> feat(ui-markdown-editor): heading wysiwyg - #346

packages/storybook/src/stories/3-ConcertoForm.stories.js, packages/ui-concerto/src/components/concertoForm.css, packages/ui-concerto/src/components/concertoForm.js, packages/ui-concerto/src/components/concertoModelBuilder.js, packages/ui-concerto/src/components/fields.js, packages/ui-concerto/src/formgenerator.js, packages/ui-concerto/src/modelBuilderVisitor.js, packages/ui-concerto/src/reactformvisitor.js
Signed-off-by: TC5022 <tanyac5022002@gmail.com>
Added a text-only prop that provides a succinct version of the concerto-form so that it is compact and easier to read.
Props added:
`textOnly`- builds on the readOnly prop and provides a compact view
Changed all the form fields including inputs, dropdowns, checkboxes, array elements, etc. Furthermore, styled the input fonts and colors so that it is convenient for the user to go through and read the form.
=> feat(ui-concerto): add textOnly mode-#13

README.md
Signed-off-by: tech-bash airiraghav@gmail.com
Changed the Slack link to Discord link for Web-Components/Readme.md
- Issue  #[ Update Slack References to Discord #388](https://github.com/accordproject/techdocs/issues/388)
=> fix(docs): Update Slack to Discord - #388 

packages/storybook/src/stories/7-Library.stories.js, packages/ui-components/src/Library/index.js
Signed-off-by: TC5022 <tanyac5022002@gmail.com>
Added a dropdown that filters templates based on their cicero version.
Added a filter that uses the cicero version of the templates by building on PR [#187](https://github.com/accordproject/web-components/pull/187). 
- <ONE> Added a cicero version in the items data in the library component after confirming that the metadata from templates contains their corresponding cicero version as can be seen [here](https://github.com/accordproject/cicero-template-library/blob/master/views/template.njk#L32).
- <TWO> Styled a dropdown for the same.
- <THREE> The filter works even if some of the items in the library do not return a cicero version. This can be confirmed through the demo itself because one of the items in the data does not contain a cicero …
=> feat(ui-components): filter templates by cicero version - #67

.github/workflows/build-and-deploy.yml
Creates an GitHub "Action" to build and deploy to AWS S3.
Requires the following "SECRETS" to be specified in GitHub.
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY
AWS_S3_BUCKET
Will need to add the following secrets to the repo.
AWS_CLOUDFRONT_DISTRIBUTION_ID : EHOZMSZP988SV
AWS_REGION : us-east-1
The invalidation is created after each deployment to S3 and can be seen here:
https://console.aws.amazon.com/cloudfront/v3/home?region=us-east-1#/distributions/EHOZMSZP988SV/invalidations
The S3 Bucket URL for testing is:
http://web-components.accordproject.org.s3-website-us-east-1.amazonaws.com/
The CloudFront Distro URL for testing is:
https://d39ci3wc10irbe.cloudfront.net/
=> chore(github) - add action to deploy to AWS S3

packages/ui-markdown-editor/src/FormattingToolbar/TableModal.js, packages/ui-markdown-editor/src/FormattingToolbar/index.js, packages/ui-markdown-editor/src/components/icons/col.js, packages/ui-markdown-editor/src/components/icons/deleteCol.js, packages/ui-markdown-editor/src/components/icons/deleteRow.js, packages/ui-markdown-editor/src/components/icons/deleteTable.js, packages/ui-markdown-editor/src/components/icons/index.js, packages/ui-markdown-editor/src/components/icons/row.js, packages/ui-markdown-editor/src/components/icons/table.js, packages/ui-markdown-editor/src/components/index.js, packages/ui-markdown-editor/src/index.js, packages/ui-markdown-editor/src/plugins/withTables.js, packages/ui-markdown-editor/src/utilities/constants.js, packages/ui-markdown-editor/src/utilities/schema.js
Signed-off-by: TC5022 <tanyac5022002@gmail.com>
Extended the current markdown-editor UI to support, render and edit tables.
- <ONE> Added various SVG icons which are consistent with the icons currently present.
- <TWO> Added a table modal that allows the user to perform various functions like adding and deleting rows and columns
- <THREE> Added support to render tables and navigate them using keyboard arrows
https://user-images.githubusercontent.com/75262300/153654435-1665a686-84b7-4adf-a102-475906654d62.mp4
=> feat(ui-markdown-editor): add support for tables-#39

packages/ui-markdown-editor/src/index.js
The fix was simple. The main issue was due to padding of ap-rich-text-editor. I think @irmerk already mentioned it .I just created a parent div added the padding and border of ap-rich-text-editor to it and it fixed the issue.
observed Behavior: [link](https://www.loom.com/share/6bd037d8267f466d833fa9e91913b6a9?sid=1912f6c3-9c8b-41bf-9b22-d370ab260074)
Fixed behavior:[Link](https://www.loom.com/share/6bb61ed53f084d6c993066e49a3a4222?sid=7aee13d5-f0ca-42e4-8626-93e87598836d)
=> fix(storybook): Possible to split paragraphs in half with drag and drop
